name: release-new-version
run-name: Build container, run all tests, do release
on:
  workflow_dispatch:
  push:
    tags:
      release-*

jobs:
  create-container:
    uses: ./.github/workflows/container.yml

  run-all-tests:
    needs: create-container
    uses: ./.github/workflows/tests_all.yml

  create-release:  
    runs-on: ubuntu-latest
    needs: run-all-tests
    steps:
      - uses: ncipollo/release-action@v1
        with:
          draft: true
