name: release-new-version
run-name: Build container, run all tests, do release
on:
  workflow_dispatch:
  pull_request:

jobs:
    run-all-tests:
      #uses: lehtiolab/ddamsproteomics/.github/workflows/tests_all.yml
      uses: ./.github/workflows/single_test.yml

    create-release:  
        runs-on: ubuntu-latest
        needs: [run-all-tests]
        steps:
          - name: Test
            run: echo This is working
