name: release-new-version
run-name: Build container, run all tests, do release
on:
  workflow_dispatch:
  push:
    tags:
      release-*

jobs:
  create-container:
    uses: ./.github/workflows/container.yml

  run-all-tests-sage:
    needs: create-container
    with:
      SEARCH: sage
    uses: ./.github/workflows/tests_all.yml

  run-all-tests-msgf:
    needs: create-container
    with:
      SEARCH: msgf
    uses: ./.github/workflows/tests_all.yml

  create-release:  
    runs-on: ubuntu-latest
    needs: [run-all-tests-sage, run-all-tests-msgf]
    steps:
      - uses: ncipollo/release-action@v1
        with:
          draft: true
          generateReleaseNotes: true
